title: हिंदी कहानी
description: प्रेरणादायक जीवनियाँ और ऐतिहासिक कहानियाँ
url: "https://hindikahani.github.io"
baseurl: "" # GitHub Pages root

# Theme
theme: minima

# Plugins for SEO and performance
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Author info (optional but good for SEO)
author:
  name: "आपका नाम"
  email: "aap@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Defaults (to avoid writing layout every time)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
