title: हिंदी कहानी
description: प्रेरणादायक जीवनियाँ और ऐतिहासिक कहानियाँ
url: "https://hindikahani.github.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

author:
  name: "आपका नाम"
  email: "aap@example.com"

markdown: kramdown
highlighter: rouge
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
