title: हिंदी कहानी
description: प्रेरणादायक हिंदी कहानियाँ, ऐतिहासिक कहानियाँ, और लोकप्रिय व्यक्तियों की जीवनियाँ।
author: मुशाहिद रज़ा
email: raza_mushahid@yahoo.com
baseurl: "" # for GitHub Pages
url: "https://hindikahani.github.io"

theme: null

markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-seo-tag

# SEO Tag Config
lang: hi
timezone: Asia/Kolkata

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Google Search Console or Analytics (optional)
google_site_verification: "" # अपना कोड डालें अगर चाहिए

# Social (optional)
# अपनी सोशल मीडिया प्रोफाइल के उपयोगकर्ता नाम यहाँ डालें
twitter:
  username: ""
github:
  username: ""
# facebook:
#   username:
# instagram:
#   username:
