title: हिंदी कहानी
description: प्रेरणादायक और ऐतिहासिक कहानियाँ – और पॉपुलर जीवनी
author: आपका नाम
email: your@email.com
baseurl: "" # for GitHub Pages
url: "https://hindikahani.github.io"

theme: null
markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-seo-tag

# SEO Tag Config
lang: hi
timezone: Asia/Kolkata

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Google Search Console or Analytics (optional)
google_site_verification: "" # Apna code daalein agar chahiye

# Social (optional)
twitter:
  username: ""
  
